# Generated by Django 5.2.1 on 2025-06-04 10:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_remove_order_items_cafe_is_active_menuitem_is_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cafe",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cafe",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
