# Generated by Django 5.2.1 on 2025-06-05 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_cafe_created_at_cafe_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="cafe",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="api.cafe",
            ),
        ),
    ]
