# Generated by Django 5.2.1 on 2025-06-13 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_alter_order_cafe"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="menuitem",
            name="image",
        ),
        migrations.AddField(
            model_name="cafe",
            name="banner_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="cafe",
            name="rating",
            field=models.DecimalField(decimal_places=1, default=4.7, max_digits=3),
        ),
        migrations.AddField(
            model_name="cafe",
            name="reviews",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="cafe",
            name="slug",
            field=models.SlugField(blank=True, max_length=60, unique=True),
        ),
        migrations.AddField(
            model_name="cafe",
            name="tagline",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="dietary",
            field=models.CharField(
                blank=True,
                choices=[("veg", "Veg"), ("non_veg", "Non-Veg"), ("vegan", "Vegan")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="food_image_url",
            field=models.URLField(
                blank=True, help_text="URL of the food image", null=True
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[("counter", "Pay at Counter"), ("online", "Online Payment")],
                default="counter",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cafe",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="cafe",
            name="owner_id",
            field=models.CharField(
                help_text="Clerk user ID who owns this cafe", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name="order",
            name="cafe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="api.cafe",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("preparing", "Preparing"),
                    ("ready", "Ready"),
                    ("completed", "Completed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_items",
                to="api.menuitem",
            ),
        ),
        migrations.AlterField(
            model_name="table",
            name="number",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name="table",
            unique_together={("cafe", "number")},
        ),
        migrations.CreateModel(
            name="Bill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("issued_at", models.DateTimeField(auto_now_add=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bill",
                        to="api.order",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "cafe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to="api.cafe",
                    ),
                ),
            ],
            options={
                "unique_together": {("cafe", "name")},
            },
        ),
        migrations.AddField(
            model_name="menuitem",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="items",
                to="api.category",
            ),
        ),
    ]
