# Generated by Django 5.2.1 on 2025-06-13 12:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_remove_menuitem_image_cafe_banner_url_cafe_rating_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cafe",
            name="reviews",
            field=models.PositiveIntegerField(default=969),
        ),
    ]
