# Generated by Django 5.2.1 on 2025-06-13 12:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_alter_cafe_reviews"),
    ]

    operations = [
        migrations.AddField(
            model_name="cafe",
            name="openingTime",
            field=models.TimeField(
                blank=True, default="09:00", help_text="Opening time in HH:MM format"
            ),
        ),
    ]
