# Generated by Django 5.2.1 on 2025-06-13 12:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_cafe_openingtime"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cafe",
            old_name="banner_url",
            new_name="bannerUrl",
        ),
    ]
