# Generated by Django 5.2.1 on 2025-06-14 03:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_alter_cafe_openingtime"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="isSpecial",
            field=models.BooleanField(default=False),
        ),
    ]
