# Generated by Django 5.2.1 on 2025-06-14 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0010_menuitem_isspecial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menuitem",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="items",
                to="api.category",
            ),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="isSpecial",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
